### ISSUE TITLE
App Rename

### ISSUE THREAD

**Issue by sschueller** [sschueller/peertube-android#132]
I have decided to rename the app to prevent confusion between the official PeerTube project and this project. 

The new name will be "Thorium". as in element 90 in the periodic table. 

The next release will reflect this and there will also be a new App Icon. The package name will remain for now but will be changed before final release.

Updates to the Play Store and f-droid will follow shortly.

**Comment by sschueller** [comment]
![ic_launcher_round](https://user-images.githubusercontent.com/1180107/52904164-74baf180-3228-11e9-8883-e2a979b928d2.png)

**Comment by lishoujun** [comment]
how about Tubedroid instead Thorium in future?  It is more meaningful

**Comment by KopfKrieg** [comment]
With "PeerTube" as name everyone knew exactly what the app was doing, but Thorium is just confusing (including the new icon, sorry).

Tubedroid isn't really an alternative, because, as recently seen with DavDroid (now DavX5), the suffix -droid shouldn't be used (but we could name it TubeX5).

Any alternatives? And maybe an icon more representing some kind of player? And of course, what does @sschueller think about changing the name (and icon) again?

**Comment by sschueller** [comment]
I can't use the name PeerTube. The icon I can change to something else, suggestions welcome. Thorium is trademark safe but I am open to other names. I would discourage using the word "droid" in the name as it becomes and issue with Lucas Film's trademark. I own the trademark "Techdroid" and it was a lot of work to get it.

**Comment by DI555** [comment]
@sschueller , what do you think about 'TubePeer'  ;) ?

**Comment by PoorPocketsMcNewHold** [comment]
Also, We can posibly just list his description in rge rest of the names in the other stores, like "Thorium, an unofficial peertube client.".
