### ISSUE TITLE
Easy way to add new servers to the app source code

### ISSUE THREAD

**Issue by niccokunzmann** [sschueller/peertube-android#286]
It would be great to
- have it easy to add Server instances
- open the App when visiting a known server url

Ideally, I would like see a list of Servers and add them easily, have it automated that Server URLs are updated when a new peertube Server is installed somewhere.

I think a .yml file or a .txt Server url list would be cool.

**Comment by sschueller** [comment]
The list of server instances you can search for in the address book is always up to date. It talks directly to the official peertube server index.

As for opening the app directly from a link. This is difficult and I have actually opened an issue at peertube because of this. In essence it is impossible to keep a complete list urls to listen for intents in the app. What is needed is a global share domain that is the same for all instances and that enables one to redirect to the correct instance. It's doable but requires someone to write the code.

https://github.com/Chocobozzz/PeerTube/issues/1540

**Comment by niccokunzmann** [comment]
Thanks for the answer, I think, this can be closed as care is taken of it elsewhere.

Am 23. April 2022 10:52:55 MESZ schrieb Stefan ***@***.***>:
